#!/usr/bin/python

import sys

try:
  from ganeti import constants
except ImportError:
  sys.stderr.write("Cannot import the python 'ganeti' module\n")
  sys.exit(1)

ganeti_version = constants.RELEASE_VERSION
needed_version = "2.1.1"

if ganeti_version < needed_version:
  sys.stderr.write("Ganeti >= %s required. %s found.\n" %
                   (needed_version, ganeti_version))
  sys.exit(1)
