#!/usr/bin/python

import sys

from ganeti import constants

ganeti_version = constants.RELEASE_VERSION
needed_version = "2.1.1"

if ganeti_version < needed_version:
  sys.stderr.write("Ganeti >= %s required. %s found.\n" %
                   (needed_version, ganeti_version))
  sys.exit(1)
