#!/bin/bash

set -e

tmpdir=$(mktemp -d -t gntbuild.XXXXXXXX)
trap "rm -rf $tmpdir" EXIT

cp -r scripts lib test $tmpdir
mv $tmpdir/lib $tmpdir/ganeti_nbma
cp -r ganeti.git/lib $tmpdir/ganeti

cd $tmpdir && "$@"
